// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  standards: [
    {
      type: 'autogenerated',
      dirName: '.' // '.' means the current docs folder
    }
  ]
}

module.exports = sidebars
